apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: t6tro9rbt-nodejs-gitops
  description: This is GitOps manifest for t6tro9rbt-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: t6tro9rbt-nodejs
    backstage.io/kubernetes-id: t6tro9rbt-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: t6tro9rbt-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:t6tro9rbt-nodejs
